# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Voice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Voice
  pod 'Alamofire'
  pod 'RNCryptor', '~> 5.1.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SDWebImage', '~> 5.3.1'
  pod 'Keychain', '~> 0.3.1'
  pod 'MJRefresh', '~> 3.5.0'
  pod 'youtube-ios-player-helper', '~> 1.0'
  pod 'ReachabilitySwift'
  pod 'Firebase/Analytics'
  target 'VoiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VoiceUITests' do
    # Pods for testing
  end

end
